apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=DummyDB;Username=dummy;Password=password123"
