apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=167.86.127.213;Port=30432;Username=admin;Password=password123;Database=mydb"
