apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummyk8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dummyk8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummyk8s-clusterip
                port:
                  number: 80
